### ISSUE TITLE
increasing the resolution of the output image

### ISSUE THREAD

**Issue by ghost** [petereigenschink/steganography.js#4]

**Comment by petereigenschink** [comment]
What exactly do you mean by that? Using default options the output image has exactly the same resolution as the input image.

Please clarify your exact use case, so that I know what you would like me to improve.

**Comment by ghost** [comment]
About the use case, I got a pretty nice idea while I was going through your code. I used your website to convert a 1740x900 px (226KB) JPEG image and the output was 290x150 px (16KB) image. There is a huge quality drop.

**Comment by petereigenschink** [comment]
The reason that on my website the output image has that drop in resolution is that the input image is scaled down. If you use steganography.js with an image which has its original size the resolution of the output image will be the same.
Anyway, I see what you mean and I will look into it.

**Comment by ghost** [comment]
Thank you so much :100:
