### ISSUE TITLE
Convert to es6 module

### ISSUE THREAD

**Issue by backspaces** [petereigenschink/steganography.js#8]
I recently downloaded and converted steganography.js to be an es6 module.
You can see it here:
https://github.com/backspaces/agentscript/blob/master/vendor/steganography.js#L1

I don't know if you are interested in using this sort of thing. I used a simple imagePromise utility import below 
```
export function imagePromise(url) {
    return new Promise((resolve, reject) => {
        const img = new Image()
        img.crossOrigin = 'Anonymous'
        img.onload = () => resolve(img)
        img.onerror = () => reject(`Could not load image ${url}`)
        img.src = url
    })
}
```
You could remove the dependency, replacing it with that code, or similar.

This isn't just es6 conversion, it corrects a problem with async vs sync image loading:
```
        loadImg: async function (url) {
            var image = await asutils.imagePromise(url)
            return image
        },
```
.. which in turn requires async/await which are only available in modules, sigh!

Anyway, if you'd like help with any of this, just ask.

**Comment by chrisfusillo** [comment]
@backspaces do you still have this conversion? :)

**Comment by backspaces** [comment]
Alas no, we decided to build a simpler one with options for the number of bits used for the data.
https://github.com/backspaces/agentscript/blob/master/src/steg.js

We specify the number of bits used in the 3 rgb channels. So using 323 we get a byte per pixel.

**Comment by hyundotio** [comment]
https://www.npmjs.com/package/steganographer I just made a project here that maybe helpful!
https://github.com/hyundotio/steganographer

@m5k

**Comment by backspaces** [comment]
Nice!
